name: Build Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    
    steps:        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Get Jenkins latest version
        id: get_version
        run: |
          echo "::set-output name=version::${{ steps.vars.outputs.tag }}"
          SHA=$(curl -q -fsSL "https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-war/${{ steps.vars.outputs.tag }}/jenkins-war-${{ steps.vars.outputs.tag }}.war.sha256" )
          echo "::set-output name=sha::${SHA}"
            
      - name: Build and push
        uses: docker/build-push-action@v2
        if: steps.get_version.outputs.version != ''
        with:
          file: ./Dockerfile
          context: .
          platforms: linux/arm64, linux/amd64
          build-args: |
            JENKINS_VERSION=${{ steps.get_version.outputs.version }}
            JENKINS_SHA=${{ steps.get_version.outputs.sha }}
          push: true
          no-cache: true
          tags: |
            ${{ secrets.DOCKER_NS }}/jenkins:${{ steps.get_version.outputs.version }}
            ${{ secrets.DOCKER_NS }}/jenkins:latest
